package com.busecarik.asteroidsgl;

public class Config {
    static final String SOUNDS_PREF_KEY = "sounds_pref_key";
    static final String MUSIC_PREF_KEY = "music_pref_key";
    static final int MAX_STREAMS = 5;
    static final float DEFAULT_MUSIC_VOLUME = 0.6f;
    static final float DEFAULT_VOLUME = 1.0f;
    final static String BACKGROUND_MUSIC = "sfx/background.mp3";
    final static String GAME_OVER = "sfx/gameOver.wav";
    final static String START_LEVEL = "sfx/startGame.wav";
    final static String BULLET = "sfx/bullet.mp3";
    final static String EXPLOSION = "sfx/explosion.wav";
    public static final int PLAYER_HEALTH = 3;
    public static final float VEL_SMALL = 15f;
    public static final float VEL_MEDIUM = 10f;
    public static final float VEL_LARGE = 5f;
    static final float TEXT_HEIGHT = 8f;
    static final float TEXT_SCORE = 160f/2+12;
    static final float TEXT_HEALTH = 30f;
    static final float TEXT_LEVEL = 160f-5;
    static final float TEXT_FPS = 22;
    static final float SCORE_TEXT = 160f/2-8;
    static final float LEVEL_TEXT = 160f-24;
    final static int HYPERSPACE_TEXT = 40;
    final static int FPS_TIMER = 1000;
    static final int VERTEX_SHADER_CODE = R.raw.vertex_shader_code;
    static final int FRAGMENT_SHADER_CODE = R.raw.fragment_shader_code;
    public static final float TIME_TO_LIVE = 3.0f; //seconds
    public static final float TIME_TO_LIVE_PARTICLE = 2.0f; //seconds
    public static final int POINT = 5;
    public static final String HYPERSPACE_ON = "on";
    public static final String HYPERSPACE_OFF = "off";
    public static final float ROTATION_VELOCITY = 360f;
    public static final float THRUST = 8f;
    public static final float DRAG = 0.99f;
    public static final float TIME_BETWEEN_SHOTS = 0.25f; //seconds.
    public static final float PLAYER_WIDTH = 4f;
    public static final float PLAYER_HEIGHT = 8f;
    public final static int SCORE_GOAL = 5000;
    public final static int TIME_FOR_HYPERSPACE = 750;
    public static final float PLAYER_OUT_OF_BOUNDS = -10;
    public static final float SMALL_SCALE = 0.25f;
    public static final float MEDIUM_SCALE = 0.50f;
    public static final float LARGE_SCALE = 0.75f;
    public static final float ASTEROID_SIZE = 12f;
    public static final float SPEED = 120f;
    static final int OFFSET = 0; //just to have a name for the parameter
    static final int LARGE_SCORE = 20;
    static final int MEDIUM_SCORE = 50;
    static final int SMALL_SCORE = 100;
    final static int STAR_COUNT = 100;
    static final int PARTICLE_COUNT = 10;
    static final float BG_COLOR[] = {0f, 0f, 0f, 1f}; //RGBA
    public static float WORLD_WIDTH = 160f; //all dimensions are in meters
    public static float WORLD_HEIGHT = 90f;
    static float METERS_TO_SHOW_X = 160f; //160m x 90m, the entire game world in view
    static float METERS_TO_SHOW_Y = 90f;
    private static long SECOND_IN_NANOSECONDS = 1000000000;
    static float NANOSECONDS_TO_SECONDS = 1.0f / SECOND_IN_NANOSECONDS;
}
